[package]
name = "day05"
version = "0.1.0"
authors = ["Ward Fenton <ward.fenton@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
itertools = "0.10.3"
